# Generated by Django 4.2.20 on 2025-05-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="has_messages",
            field=models.BooleanField(default=False),
        ),
    ]
