# Generated by Django 4.2.20 on 2025-05-30 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_listing_archived'),
        ('chat', '0002_chat_has_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='listing.listing'),
        ),
        migrations.AddField(
            model_name='message',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
