# Generated by Django 4.2.20 on 2025-07-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        ("chat", "0002_chat_has_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="marketplace.listing",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(max_length=400),
        ),
    ]
