# Generated by Django 4.2.20 on 2025-06-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_reply_to_alter_message_reply_to_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(max_length=400),
        ),
    ]
