# Generated by Django 4.2.18 on 2025-01-17 19:10

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image.models.PathName('images'))),
                ('image_name', models.CharField(max_length=100, unique=True)),
                ('image_type', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100, unique=True)),
                ('container', models.CharField(max_length=20)),
            ],
        ),
    ]
