# Generated by Django 4.2.20 on 2025-05-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="banner",
        ),
    ]
