# Generated by Django 4.2.20 on 2025-05-11 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("major", models.CharField(blank=True, max_length=50, null=True)),
                ("semester", models.SmallIntegerField(blank=True, null=True)),
                ("instagram", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
