# Generated by Django 4.2.19 on 2025-03-13 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_email_verified_at_user_phone_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
