# Generated by Django 4.2.19 on 2025-03-13 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_verificationdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
