# Generated by Django 4.2.20 on 2025-06-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_userinformation_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
