# Generated by Django 4.2.20 on 2025-06-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="country_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
