# Generated by Django 4.2.20 on 2025-06-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_user_country_code_remove_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_verified_at",
        ),
    ]
