# Generated by Django 4.2.20 on 2025-06-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_remove_user_phone_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="university",
            field=models.CharField(default="anahuacmayab.edu.mx", max_length=20),
            preserve_default=False,
        ),
    ]
