# Generated by Django 4.2.20 on 2025-07-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_user_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
