MAJORS_LIST = [
    ('arq', 'Arquitectura'),
    ('com', 'Comunicación'),
    ('dir', 'Dirección de empresas de entretenimiento'),
    ('dmo', 'Diseño de moda e innovación'),
    ('dgr', 'Diseño gráfico'),
    ('din', 'Diseño industrial'),
    ('dmu', 'Diseño multimedia'),
    ('ri', 'Relaciones internacionales'),
    ('der', 'Derecho'),
    ('inga', 'Ingeniería ambiental'),
    ('inges', 'Ingeniería en Energías Sustentables'),
    ('ingbio', 'Ingeniería Biomédica'),
    ('ingti', 'Ingeniería en Tecnologías de la Información'),
    ('ingad', 'Ingeniería en Animación Digital'),
    ('ingmec', 'Ingeniería Mecatrónica'),
    ('ingciv', 'Ingeniería Civil'),
    ('ingind', 'Ingeniería Industrial'),
    ('admin', 'Administración de empresas'),
    ('dep', 'Dirección del deporte'),
    ('fin', 'Finanzas'),
    ('merc', 'Mercadotecnia'),
    ('neg', 'Negocios internacionales'),
    ('gastro', 'Gastronomía'),
    ('turismo', 'Turismo'),
    ('biotec', 'Biotecnología'),
    ('psico', 'Psicología'),
    ('psicped', 'Psicopedagogía'),
    ('medcir', 'Médico Cirujano'),
    ('medcirdent', 'Médico Cirujano Dentista'),
    ('nutri', 'Nutrición'),
    ('terap', 'Terapia física'),
]

UNIVERSITIES = {
    'anahuacmayab.edu.mx': 'Anáhuac Mayab'
}