# Generated by Django 4.2.20 on 2025-07-11 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0007_alter_location_radius'),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('sports', 'Sports'), ('food', 'Food'), ('scholar', 'Scholar'), ('vehicles', 'Vehicles'), ('property_rentals', 'Property_rentals'), ('other', 'Other'), ('music', 'Music')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used', models.BooleanField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=5)),
                ('sell', models.BooleanField(default=False)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('studio', 'Studio'), ('room only', 'Room Only')], max_length=9)),
                ('bedrooms', models.SmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.SmallIntegerField(blank=True, null=True)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='marketplace.listing')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='location.location')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.image')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.listing')),
            ],
        ),
    ]
