# Generated by Django 4.2.20 on 2025-05-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
