# Generated by Django 4.2.19 on 2025-03-04 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('about', models.CharField(max_length=500)),
                ('customizable', models.BooleanField(default=False)),
                ('ready_to_ship', models.BooleanField(default=False)),
                ('made_to_order', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_units', models.SmallIntegerField()),
                ('max_units', models.SmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
            ],
        ),
    ]
