# Generated by Django 4.2.20 on 2025-04-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_latitude_location_longitude_and_more'),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='stock',
        ),
        migrations.AddField(
            model_name='listing',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('sports', 'Sports'), ('scholar', 'Scholar'), ('vehicles', 'Vehicles'), ('property_rentals', 'Property_rentals')], max_length=50),
        ),
        migrations.CreateModel(
            name='PropertyRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aproximate_location', models.BooleanField(default=True)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Townhouse', 'Townhouse'), ('Villa', 'Villa'), ('Studio', 'Studio'), ('Room Only', 'Room Only')], max_length=9)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_rental', to='listing.listing')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_rentals', to='location.location')),
            ],
        ),
    ]
