# Generated by Django 4.2.20 on 2025-04-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_listing_stock_listing_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrental',
            name='sell',
            field=models.BooleanField(default=False),
        ),
    ]
