# Generated by Django 4.2.19 on 2025-03-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='made_to_order',
        ),
    ]
