# Generated by Django 4.2.20 on 2025-04-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_remove_location_city_remove_location_country_and_more"),
        ("listing", "0003_propertyrental_sell"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PropertyRental",
            new_name="PropertyListing",
        ),
    ]
