# Generated by Django 4.2.20 on 2025-04-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_remove_location_city_remove_location_country_and_more"),
        ("listing", "0004_rename_propertyrental_propertylisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylisting",
            name="bathrooms",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertylisting",
            name="bedrooms",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertylisting",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property",
                to="listing.listing",
            ),
        ),
        migrations.AlterField(
            model_name="propertylisting",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property",
                to="location.location",
            ),
        ),
    ]
