# Generated by Django 4.2.19 on 2025-03-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_listingimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='about',
            new_name='description',
        ),
    ]
