# Generated by Django 4.2.20 on 2025-04-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0005_alter_propertylisting_bathrooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="used",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
