# Generated by Django 4.2.19 on 2025-03-17 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingprice',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='listing.listing'),
        ),
    ]
