# Generated by Django 4.2.20 on 2025-04-24 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0006_alter_listing_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertylisting",
            name="aproximate_location",
        ),
    ]
