# Generated by Django 4.2.20 on 2025-04-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0007_remove_propertylisting_aproximate_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylisting",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("townhouse", "Townhouse"),
                    ("villa", "Villa"),
                    ("studio", "Studio"),
                    ("room only", "Room Only"),
                ],
                max_length=9,
            ),
        ),
    ]
