# Generated by Django 4.2.20 on 2025-04-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0008_alter_propertylisting_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylisting",
            name="time_unit",
            field=models.CharField(
                choices=[("day", "Day"), ("week", "Week"), ("month", "Month")],
                default="month",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
