# Generated by Django 4.2.19 on 2025-04-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_listingsizespecification_listingsize_listingcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='clothes', max_length=50),
            preserve_default=False,
        ),
    ]
