# Generated by Django 4.2.20 on 2025-05-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_propertylisting_time_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('sports', 'Sports'), ('food', 'Food'), ('scholar', 'Scholar'), ('vehicles', 'Vehicles'), ('property_rentals', 'Property_rentals')], max_length=50),
        ),
    ]
