# Generated by Django 4.2.19 on 2025-04-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingsize',
            old_name='specification',
            new_name='specifications',
        ),
    ]
