# Generated by Django 4.2.19 on 2025-04-03 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_rename_specification_listingsize_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingcolor',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listingsize',
            name='listing',
        ),
        migrations.CreateModel(
            name='ListingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.listingcolor')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='listing.listing')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.listingsize')),
            ],
        ),
    ]
