# Generated by Django 4.2.20 on 2025-05-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
