# Generated by Django 4.2.19 on 2025-04-03 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_remove_listingcolor_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingoptions',
            old_name='color',
            new_name='colors',
        ),
        migrations.RemoveField(
            model_name='listingoptions',
            name='size',
        ),
        migrations.AddField(
            model_name='listingoptions',
            name='sizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.listingsize'),
        ),
    ]
