# Generated by Django 4.2.20 on 2025-06-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0011_listing_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylisting",
            name="air_conditioning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="furnished",
            field=models.BooleanField(default=False),
        ),
    ]
