# Generated by Django 4.2.20 on 2025-06-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_propertylisting_air_conditioning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('sports', 'Sports'), ('food', 'Food'), ('scholar', 'Scholar'), ('vehicles', 'Vehicles'), ('property_rentals', 'Property_rentals'), ('other', 'Other'), ('music', 'Music')], max_length=50),
        ),
    ]
