# Generated by Django 4.2.19 on 2025-04-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_rename_color_listingoptions_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingoptions',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='listingoptions',
            name='sizes',
        ),
        migrations.AddField(
            model_name='listingoptions',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='listing.listingcolor'),
        ),
        migrations.AddField(
            model_name='listingoptions',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='listing.listingsize'),
        ),
    ]
