# Generated by Django 4.2.19 on 2025-04-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_remove_listingoptions_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingoptions',
            name='colors',
            field=models.ManyToManyField(to='listing.listingcolor'),
        ),
        migrations.AlterField(
            model_name='listingoptions',
            name='sizes',
            field=models.ManyToManyField(to='listing.listingsize'),
        ),
    ]
