# Generated by Django 4.2.19 on 2025-04-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_alter_listingoptions_colors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingoptions',
            old_name='model',
            new_name='models',
        ),
    ]
