# Generated by Django 4.2.19 on 2025-04-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0015_rename_model_listingoptions_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="stock",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
