export const MAJORS_LIST = [
    { value: 'admin', name: 'Administración de empresas' },
    { value: 'arq', name: 'Arquitectura' },
    { value: 'biotec', name: 'Biotecnología' },
    { value: 'com', name: 'Comunicación' },
    { value: 'der', name: 'Derecho' },
    { value: 'dgr', name: 'Diseño gráfico' },
    { value: 'din', name: 'Diseño industrial' },
    { value: 'dmo', name: 'Diseño de moda e innovación' },
    { value: 'dmu', name: 'Diseño multimedia' },
    { value: 'dir', name: 'Dirección de empresas de entretenimiento' },
    { value: 'dep', name: 'Dirección del deporte' },
    { value: 'fin', name: 'Finanzas' },
    { value: 'gastro', name: 'Gastronomía' },
    { value: 'inga', name: 'Ingeniería ambiental' },
    { value: 'ingad', name: 'Ingeniería en Animación Digital' },
    { value: 'ingbio', name: 'Ingeniería Biomédica' },
    { value: 'ingciv', name: 'Ingeniería Civil' },
    { value: 'inges', name: 'Ingeniería en Energías Sustentables' },
    { value: 'ingind', name: 'Ingeniería Industrial' },
    { value: 'ingmec', name: 'Ingeniería Mecatrónica' },
    { value: 'ingti', name: 'Ingeniería en Tecnologías de la Información' },
    { value: 'merc', name: 'Mercadotecnia' },
    { value: 'medcir', name: 'Médico Cirujano' },
    { value: 'medcirdent', name: 'Médico Cirujano Dentista' },
    { value: 'neg', name: 'Negocios internacionales' },
    { value: 'nutri', name: 'Nutrición' },
    { value: 'psico', name: 'Psicología' },
    { value: 'psicped', name: 'Psicopedagogía' },
    { value: 'ri', name: 'Relaciones internacionales' },
    { value: 'terap', name: 'Terapia física' },
    { value: 'turismo', name: 'Turismo' },
]