# Generated by Django 4.2.20 on 2025-04-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
                ('number', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
