# Generated by Django 4.2.20 on 2025-04-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_location_latitude_location_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aproximatelocation",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aproximate_location",
                to="location.location",
            ),
        ),
    ]
