# Generated by Django 4.2.20 on 2025-04-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_aproximatelocation_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='number',
        ),
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
        migrations.RemoveField(
            model_name='location',
            name='street',
        ),
        migrations.RemoveField(
            model_name='location',
            name='zip_code',
        ),
        migrations.DeleteModel(
            name='AproximateLocation',
        ),
    ]
