# Generated by Django 4.2.20 on 2025-04-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_remove_location_city_remove_location_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="radius",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=2, null=True
            ),
        ),
    ]
