# Generated by Django 4.2.20 on 2025-04-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_location_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="radius",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
