# Generated by Django 4.2.20 on 2025-04-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0006_alter_location_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="radius",
            field=models.SmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
