# Generated by Django 4.2.20 on 2025-07-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("average_rating", models.FloatField()),
                ("recommendation_rate", models.FloatField()),
                ("department", models.CharField()),
                ("difficulty_level", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("HG", "Califica Duro"),
                            ("BO", "Barco"),
                            ("LOH", "Muchas tareas"),
                            ("R", "Prepárate para leer"),
                            ("OA", "Asistencia obligatoria"),
                            ("LONG", "Las clases son largas"),
                            ("LE", "Pocos exámenes"),
                            ("ME", "Muchos exámenes"),
                            ("LH", "Deja trabajos largos"),
                            ("HE", "Exámenes difíciles"),
                            ("LP", "Muchos proyectos"),
                            ("WTA", "Tomaría su clase otra vez"),
                            ("GFB", "Da buena retroalimentación"),
                            ("PM", "La participación importa"),
                            ("RES", "Respetado"),
                            ("INS", "Inspiracional"),
                            ("EXTRA", "Da crédito extra"),
                            ("SUP", "Brinda apoyo"),
                            ("EXC", "Clases excelentes"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("mandatory_assistance", models.BooleanField()),
                ("recommended", models.BooleanField()),
                ("clarity", models.SmallIntegerField()),
                ("help", models.SmallIntegerField()),
                ("difficulty", models.SmallIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professor_rating.course",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professor_rating.professor",
                    ),
                ),
                ("tags", models.ManyToManyField(to="professor_rating.tag")),
            ],
        ),
    ]
