# Generated by Django 4.2.20 on 2025-07-12 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professor_rating", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 12, 19, 56, 29, 682798, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="professor",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="professor",
            name="department",
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name="professor",
            name="difficulty_level",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="professor",
            name="name",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="professor",
            name="recommendation_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
