# Generated by Django 4.2.20 on 2025-07-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professor_rating", "0002_rating_created_at_alter_course_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="department",
            field=models.CharField(
                choices=[
                    ("ARQ", "Arquitectura"),
                    ("COM", "Comunicación"),
                    ("DIS", "Diseño"),
                    ("DER", "Derecho/Relaciones Internacionales"),
                    ("ING", "Ingeniería"),
                    ("NEG", "Negocios/Administración"),
                    ("TUR", "Turismo"),
                    ("GAST", "Gastronomía"),
                    ("SAL", "Salud/Medicina"),
                    ("HUM", "Humanidades"),
                    ("ESP", "Español"),
                    ("LENG", "Lenguas"),
                ],
                max_length=4,
            ),
        ),
    ]
