# Generated by Django 4.2.20 on 2025-07-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professor_rating", "0003_alter_professor_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="grade_achieved",
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
