# Generated by Django 4.2.20 on 2025-07-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("professor_rating", "0004_rating_grade_achieved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="clarity",
            new_name="quality",
        ),
    ]
