# Generated by Django 4.2.20 on 2025-07-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("professor_rating", "0005_rename_clarity_rating_quality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="help",
        ),
    ]
