# Generated by Django 4.2.20 on 2025-07-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professor_rating", "0006_remove_rating_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="grade_achieved",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(
                choices=[
                    ("HG", "Califica Duro"),
                    ("BO", "Barco"),
                    ("LOH", "Muchas tareas"),
                    ("R", "Prepárate para leer"),
                    ("OA", "Asistencia obligatoria"),
                    ("LONG", "Las clases son largas"),
                    ("LE", "Pocos exámenes"),
                    ("ME", "Muchos exámenes"),
                    ("LH", "Deja trabajos largos"),
                    ("HE", "Exámenes difíciles"),
                    ("EE", "Exámenes fáciles"),
                    ("LP", "Muchos proyectos"),
                    ("WTA", "Tomaría su clase otra vez"),
                    ("GFB", "Da buena retroalimentación"),
                    ("PM", "La participación importa"),
                    ("RES", "Respetado"),
                    ("INS", "Inspiracional"),
                    ("EXTRA", "Da crédito extra"),
                    ("SUP", "Brinda apoyo"),
                    ("EXC", "Clases excelentes"),
                ],
                max_length=5,
                unique=True,
            ),
        ),
    ]
