# Generated by Django 4.2.20 on 2025-07-13 21:26

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("professor_rating", "0007_alter_rating_grade_achieved_alter_tag_title"),
    ]

    operations = [
        UnaccentExtension()
    ]
