# Generated by Django 4.2.20 on 2025-07-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professor_rating", "0008_add_unaccent"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="rating_count",
            field=models.SmallIntegerField(default=0),
        ),
    ]
