# Generated by Django 4.2.20 on 2025-07-14 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("professor_rating", "0009_professor_rating_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="professor_rating.professor",
            ),
        ),
    ]
