# Generated by Django 4.2.20 on 2025-07-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professor_rating", "0010_alter_rating_professor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="grade_achieved",
            field=models.CharField(
                choices=[
                    ("10", "10"),
                    ("9.5", "9.5"),
                    ("9", "9"),
                    ("8.5", "8.5"),
                    ("8", "8"),
                    ("7.5", "7.5"),
                    ("7", "7"),
                    ("6.5", "6.5"),
                    ("6", "6"),
                    ("5", "5"),
                    ("DIS", "Dada de baja"),
                    ("INC", "Incompleta"),
                    ("DK", "Todavía no se"),
                    ("PN", "Prefiero no decir"),
                    ("NG", "Clase sin calificación"),
                ],
                max_length=3,
            ),
        ),
    ]
