# Generated by Django 4.2.20 on 2025-07-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_rating', '0011_alter_rating_grade_achieved'),
    ]

    operations = [
        migrations.RunSQL('''
            CREATE TEXT SEARCH CONFIGURATION spanish_unaccent( COPY=spanish );
            ALTER TEXT SEARCH CONFIGURATION spanish_unaccent ALTER MAPPING FOR hword, hword_part, word WITH unaccent, spanish_stem;
        ''')
    ]
